# Generated by Django 3.1.4 on 2021-01-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20210110_0322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifyToken',
            new_name='Spotify',
        ),
    ]
