# Generated by Django 3.1.4 on 2021-01-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_auto_20210110_0335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spotify',
            new_name='SpotifyToken',
        ),
    ]
