# Generated by Django 3.1.4 on 2021-01-14 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_current_song'),
        ('spotify', '0009_auto_20210113_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vote',
            new_name='Votes',
        ),
    ]
